<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($this->getTransactionMode() == 'sandbox' || $this->getTransactionMode() == 'test'): ?>
<div style="background-color:#FFD9B3; text-align:center;color:red; border:2px solid red; padding:1px; font-weight:bold;">
	<?php if ($this->getTransactionMode() == 'sandbox'):?>
		<?php echo $this->__('billpay_sandbox_mode_info_text') ?>
	<?php else: ?>
		<?php echo $this->__('billpay_test_mode_info_text') ?>
	<?php endif;?>	
	<br />
	<a style="" href="http://www.billpay.de/haendler/integration-plugin" target="_blank"><?php echo $this->__('billpay_switch_live_info') ?></a>
</div>
<?php endif; ?>