<div id="loadingmask" style="display: none;">
    <div class="loader" id="loading-mask-loader"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'mana/ajax-loader.gif';?>" alt="<?php echo $this->__('Loading...') ?>"/><?php echo $this->__('Loading...') ?></div>
    <div id="loading-mask"></div>
</div>
<dl class="menuDiscounts">
    <dt><?php echo $this->__('Categories'); ?></dt>
    <dd><?php echo $this->getCategoryTree();?></dd>
</dl>