<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var Billpay_Block_Info_AdditionalSepaInformation $this
 */
?>
<style type="text/css">
    #billpay_container_rat .bpy-additional-information-block {
        padding-left: 15px;
    }
    .bpy-additional-information-block {
        padding-right: 15px; /* in order to a strange padding */
        font-size: 11px;
        margin-top: 11px;
        color: #666;
    }
    .bpy-additional-information-block a {
        color: #666;
    }
    #onestepcheckout-form .bpy-additional-information-block {
        padding-left: 0;
    }
</style>
<br style="clear:both"/>
<div class="bpy-additional-information-block" style="display: none">
    <?php echo $this->__('sepa_additional_information_headline'); ?>:<br/>
    <?php echo $this->getInfoText(); ?>
</div>