<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Paymentnetwork
 * @package	Paymentnetwork_Sofortueberweisung
 * @copyright  Copyright (c) 2008 [m]zentrale GbR, 2010 Payment Network AG, 2012 initOS GmbH & Co. KG
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version	$Id: sofortueberweisung.phtml 2016 2011-10-28 15:29:24Z poser $
 */

-->
<strong><?php echo Mage::helper('pnsofortueberweisung')->__('Paymentinformations: %s',$this->getMethod()->getTitle()) ?></strong>
<br />
<?php 
$tid = $this->getMethod()->getInfoInstance()->getAdditionalInformation('sofort_transaction');
$invoice_url = $this->getMethod()->getInfoInstance()->getAdditionalInformation('sofortrechnung_invoice_url');
$invoiceData = unserialize($this->getMethod()->getInfoInstance()->getAdditionalInformation('sofort_invoice'));
$orderId = $this->getMethod()->getInfoInstance()->getOrder()->getId();

if($invoice_url != "") {
	$tid = '<a href="'.$invoice_url.'">'.$tid.' '.Mage::helper('pnsofortueberweisung')->__('click to download invoice').'</a>';
}
?>
<?php echo Mage::helper('pnsofortueberweisung')->__('Transaction Id: %s',$tid); ?><br />
<?php 
$url = Mage::helper("adminhtml")->getUrl('pnsofortueberweisung/adminhtml_pnsofortueberweisung/edit',array('order_id'=>$orderId));
// we only show the button in view mode, to avoid be embeded in a form and trigger submit
if($this->getRequest()->getActionName() == 'view' && $this->getRequest()->getControllerName() == 'sales_order'):?>
	<button onClick="setLocation('<?php echo $url; ?>')" class="button"><span><?php echo Mage::helper('pnsofortueberweisung')->__('Edit Cart'); ?></span></button>
	<br />
<?php endif; ?>
<?php 
if(!empty($invoiceData)){
    foreach($invoiceData as $label => $value){
        echo "<strong>".Mage::helper('pnsofortueberweisung')->__($label)."</strong> ";
        echo "<span>".$value."</span><br/>";
    }
}
?>
