<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table>
	<tr style="height:23px; width:130px">
		<td style="width:130px">
			<div style="padding:0px; float:left; color: #666666; width:100px">
				<?php echo $this->__('billpay_account_holder') ?>&nbsp;<span class="required">*</span>
			</div>
		</td>
		<td>
			<input class="input-text required-entry" type="text" id="<?php echo $this->getMethodCode() ?>_account_holder" name="payment[<?php echo $this->getMethodCode() ?>_account_holder]" value="<?php echo $this->getFullName() ?>" style="width:<?php echo $this->getFieldWidth()?>px" />
		</td>
	</tr>
	<tr style="height:23px">
		<td style="width:130px">
			<div style="padding:0px; float:left; color: #666666; width:100px">
				<?php echo $this->__('billpay_account_number') ?>&nbsp;<span class="required">*</span>
			</div>
		</td>
		<td>
			<input class="input-text required-entry" id="<?php echo $this->getMethodCode() ?>_account_number" autocomplete="off" name="payment[<?php echo $this->getMethodCode() ?>_account_number]" type="text" style="width:<?php echo $this->getFieldWidth()?>px" />
		</td>
	</tr>
	<tr style="height:23px">
		<td style="width:130px">
			<div style="padding:0px; float:left; color: #666666; width:100px">
				<?php echo $this->__('billpay_bank_code') ?>&nbsp;<span class="required">*</span>
			</div>
		</td>
		<td>
			<input class="input-text required-entry" id="<?php echo $this->getMethodCode() ?>_sort_code" autocomplete="off" name="payment[<?php echo $this->getMethodCode() ?>_sort_code]" type="text" style="width:<?php echo $this->getFieldWidth()?>px" />
		</td>
	</tr>
</table>
