<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!-- Mage 1.2/1.3 -->

<?php $_order = $this->getParentBlock()->getOrder() ?>
<?php if (in_array($_order->getPayment()->getMethod(), array('billpay_rec', 'billpay_elv')) && $_order->getBillpayChargedFee() > 0): ?>
<tr>
	<td colspan="3" align="right" style="padding: 3px 9px"><?php $paymentMethod = $_order->getPayment()->getMethod(); ?>
	<?php if ($paymentMethod == 'billpay_rec'):?> <?php echo Mage::helper('billpay/api')->__('billpay_rec_step_fee_text') ?>
	<?php elseif ($paymentMethod === 'billpay_elv'):?> <?php echo Mage::helper('billpay/api')->__('billpay_elv_step_fee_text') ?>
	<?php endif; ?></td>
	<?php if (Mage::helper('billpay/api')->getConfigData('fee/display_incl_tax_frontend', $_order->getStoreId())): ?>
	<td align="right" style="padding: 3px 9px"><?php echo $_order->formatPrice($_order->getBillpayChargedFee()) ?>
	</td>
	<?php else: ?>
	<td align="right" style="padding: 3px 9px"><?php echo $_order->formatPrice($_order->getBillpayChargedFeeNet()) ?>
	</td>
	<?php endif; ?>
</tr>
	<?php endif; ?>