<dt onclick="showFiltr(this)"><?php echo $this->__('Price') ?></dt>
<dd>
    <div class="clearfix"></div>
    <div class="slider slider-horizontal">
        <input id="priceSlider" type="text" class="span2" value="<?php echo (int)$this->_currentMinPrice;?>,<?php echo (int)$this->_currentMaxPrice;?>" data-slider-value="[<?php echo (int)$this->_currentMinPrice;?>,<?php echo (int)$this->_currentMaxPrice;?>]" data-slider-min="<?php echo (int)$this->_minPrice;?>" data-slider-max="<?php echo (int)$this->_maxPrice;?>" data-slider-step="1" data-slider-selection="after">
    </div>
    <b class="pull-left sliderPrices"><?php echo Mage::helper('core')->currency((int)$this->_minPrice, true, false);?></b>
    <b class="pull-right sliderPrices"><?php echo Mage::helper('core')->currency((int)$this->_maxPrice, true, false);?></b>
    <div class="clearfix"></div>
    <button id="priceFilterButton"><?php echo $this->__('Submit Prices');?></button>
    <script>
        jQuery('#priceSlider').slider();
        jQuery("#priceFilterButton").click(function()
        {
            var prices = (jQuery("#priceSlider").val()).split(',');
            filterItems('<?php echo $this->getCleanPriceSliderUrl();?>min=' + prices[0] + '&max=' + prices[1]);
        });
    </script>
</dd>