<?php $optionsHelper = Mage::helper('codevog_options');?>

<?php if (($_products = $this->getLastViewedCollection()) && $_products->getSize()): ?>
    <div class="cms-index-index">
        <div class="products-grid">
            <h2 class="subtitle"><?php echo $this->__('Lastviewed products') ?></h2>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <div class="jcarousel-wrap">
            <div class="jcarousel">
                <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
                        <?php /*if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
                <?php endif*/ ?>
                        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h3>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">
                                <?php echo $optionsHelper->getProductDiscount($_product);?>
                                <?php echo $optionsHelper->productLabels($_product);?>
                                <?php $_imgSize = 260; ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>

                            <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        </li>
                        <?php /*if ($i%$_columnCount==0 || $i==count($_products)): ?>
                </ul>
                <?php endif*/ ?>
                    <?php endforeach; ?>
                </ul>
            </div>
                <?php if(count($this->getLastViewedCollection()->getItems()) > 4 ): ?>
	                <a href="#" class="jcarousel-control-prev"></a>
	                <a href="#" class="jcarousel-control-next"></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
