<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var Billpay_Block_Form_FormRat $this
 */
?>
<style type="text/css">
    .bpy-border {
        border: 1px solid #c0c0c0;
    }
    .bpy-container {
        position: relative;
    }
    .form-list .bpy-input-row {
        min-height: 23px;
        width: 100%;
    }
</style>
<ul id="payment_form_billpay_rat" class="form-list bpy-container" style="display: none">
    <li>
        <?php echo $this->getTestModeInfoBoxHtml() ?>
    </li>
    <li id="billpay_container_rat" class="bpy-border" style="padding: 10px">
        <label for="billpay_rate_number">
            <?php echo $this->__('billpay_rate_calculation_please_enter')?>
        </label>
        <?php $preSelectedRate = $this->getBillpayRates(); ?>
        <select id="billpay_rate_number" name="payment[billpay_rates]"
                style="margin-left:5px; margin-right:4px; width:43px;"
                onchange="billpayCalculateRates('<?php echo $this->getUrl("billpay/processing/calculateRates", array("_secure" => true)) ?>')">
            <option value="">-</option>
            <?php foreach ($this->getAvailableTerms() as $term): ?>
                <option value="<?php echo $term; ?>"
                        <?php echo $term == $preSelectedRate ? 'selected="selected"' : '' ?>>
                    <?php echo $term; ?>
                </option>
            <?php endforeach; ?>
        </select>
    </li>
    <li id="billpay_rates"></li>
    <li id="billpay-rates-loading" style="display: none;">
        <div style="margin: 0 0 0 40%;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" style="margin-right:3px;" />
            <?php echo $this->__('loading_text'); ?>
        </div>
    </li>
    <li id="billpay_rat_step2" style="display: none"></li>
    <li><?php echo $this->getFraudDetectionHtml() ?></li>
</ul>
<script type="text/javascript">

	<?php if ($this->getBillpayRates() > 0): ?>
	var billpayRadioRat = $("p_method_billpay_rat");
	if (billpayRadioRat && !billpayRadioRat.isBillpayBinded) {

		var calcFunc = function() {
			$('billpay_rates').update('');
			$('billpay_rat_step2').update('');
			$('billpay-rates-loading').show();

			var request = new Ajax.Request(
				"<?php echo $this->getUrl('billpay/processing/calculateRates', array("_secure" => true)) ?>", {
					method:'post',
					onSuccess: function(transport) {
						$('billpay-rates-loading').hide();
						$('billpay_rates').update(billpayLoadResponse(transport));
					},
					onFailure: function() {
						location.href = "<?php echo $this->getUrl('checkout/cart', array("_secure" => true)) ?>";
					},
					parameters: Form.serialize(billpayGetForm())
				}
			);
		};
		
		if (typeof(billpayRadioRat.onclick) == 'function') {	// wrap existing function
			billpayRadioRat.onclick = billpayRadioRat.onclick.wrap(
				function(origMethod) {
					origMethod();
					calcFunc();
				});
		}
		else {	// attach new handler
			billpayRadioRat.onclick = function() {
				calcFunc();
			};
		}
		
		billpayRadioRat.isBillpayBinded = true;
	};
	<?php endif; ?>

</script>