<?php 
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php
    $filterUrls = Mage::helper('mana_filters/url');
$_dimHelper = Mage::helper('configurableswatches/swatchdimensions');
$_swatchInnerWidth = $_dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchInnerHeight = $_dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterWidth = $_dimHelper->getOuterWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterHeight = $_dimHelper->getOuterHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchHelper = Mage::helper('configurableswatches/data');
?>


<ol class="aaa m-filter-item-list <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
<?php foreach ($this->getItems() as $_item): ?>


    <?php
    $_isSwatch = $_swatchHelper->attrIsSwatchType($_item);
    $_hasItems = ($_item->getCount() > 0);
    $_label = $_item->getLabel();
    $_swatchUrl = Mage::helper('configurableswatches/productimg')->getGlobalSwatchUrl($_item, $_label, $_swatchInnerWidth, $_swatchInnerHeight);
    $_hasImage = (!empty($_swatchUrl));
    $_linkClass = 'swatch-link' . (($_hasImage) ? ' has-image' : '');
    $_linkCss = 'height:' . $_swatchOuterHeight . 'px; ' . ((!$_hasImage) ? 'min-' : '') . 'width:' . $_swatchOuterWidth . 'px;';
    $_lineHeight = $_swatchOuterHeight + 2;
    ?>


    <li class="<?php if ($_item->getMShowSelected()) {echo 'm-selected-ln-item'; } if ($_hasImage) {echo ' has-swatch';}   ?>">
        <?php // MANA BEGIN ?>

        <?php if (!$_item->getMSelected()): ?>
	        <?php if ($_item->getCount() > 0): ?>
	        <a class="<?php if ($_hasImage) { echo 'swatch-link-new'; } ?>" href="#" onclick="filterItems('<?php echo $filterUrls->getFilterUrl($this->urlEscape($_item->getUrl())); ?>');return false;" title="<?php echo $this->escapeHtml($_item->getLabel()) ?>">



                <?php //echo $this->escapeHtml($_item->getLabel()) ?>
                <?php if ($_hasImage): ?>
                    <span class="swatch-label-new"<?php echo ' style="' . $_linkCss . '"'; ?>>
                        <img src="<?php echo $_swatchUrl; ?>" alt="<?php echo $_label; ?>" title="<?php echo $_label ?>" width="<?php echo $_swatchInnerWidth ?>" height="<?php echo $_swatchInnerHeight ?>" />
                    </span>
                <?php else: ?>
                    <?php echo $_label; ?>
                <?php endif; ?>

                <?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
                    <span>
                        (<?php echo $_item->getCount() ?>)
                    </span>
                <?php endif; ?>
            </a>
	        <?php else: echo $this->escapeHtml($_item->getLabel()) ?>
                <?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
                    (<?php echo $_item->getCount() ?>)
                <?php endif; ?>
	        <?php endif; ?>
        <?php endif; ?>
        <?php // MANA END ?>

    </li>
<?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
