<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Paymentnetwork
 * @package	Paymentnetwork_Sofortueberweisung
 * @copyright  Copyright (c) 2008 [m]zentrale GbR, 2010 Payment Network AG
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version	$Id: infobox.phtml 3844 2012-04-18 07:37:02Z dehn $
 */
?>
<?php if(Mage::getStoreConfig('payment/pnsofortueberweisung/active')):?>
<div class="box base-mini mini-su-infobox">
	<div class="content">
		<a onclick="javascript:window.open('<?php echo $this->__('https://images.sofort.com/de/su/landing.php') ?>?banner=banner_150x200','kundeninformationen','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1020, height=900');return false;" href="#" title="Hier klicken - sofortüberweisung Kundeninformationen"><img src="<?php echo $this->__('https://images.sofort.com/de/su/banner_150x200.png') ?>" alt="Hier klicken - sofortüberweisung Kundeninformationen" border="0" /></a>
	</div>	
	<div class="actions">
		<a href="<?php echo $this->__('https://images.sofort.com/de/su/landing.php') ?>"><small><?php echo $this->__('More') ?></small></a>
	</div>
</div>
<?php endif; ?>