<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
	
	function billpayLoadingComplete_Elv(transport) {
		if (transport && transport.responseText) {
			try {
				response = eval('(' + transport.responseText + ')');
			}
			catch (e) {
				response = {};
			}
		}

		$('billpay-ajax-elv-container-loading').hide();
                    
		if (response.update_section) {
			$('billpay-ajax-container-elv').update(response.update_section.html);
		}
	}
	
	function billpayLoadingError_Elv() {
		location.href = "<?php echo $this->getUrl('checkout/cart', array("_secure" => true)) ?>";
	}
	
	function billpayPaymentSelected_Elv() {
		$('billpay-ajax-container-elv').update('');
		$('billpay-ajax-elv-container-loading').show();
		
		var request = new Ajax.Request(
			"<?php echo $this->getUrl('billpay/checkout/formElv', array("_secure" => true)) ?>",
			{
				method:'post',
				onSuccess: billpayLoadingComplete_Elv,
				onFailure: billpayLoadingError_Elv
			}
		);
	}

    var billpayRadio_Elv = $('p_method_billpay_elv');
    if (billpayRadio_Elv && !billpayRadio_Elv.isBillpayBinded) {
        billpayRadio_Elv.observe('click', function(event) {
            billpayPaymentSelected_Elv();
            billpayRadio_Elv.isBillpayBinded = true;
        })
    }

    <?php if($this->isPaymentSelected()): ?>
        billpayPaymentSelected_Elv();
    <?php endif; ?>
</script>

<ul id="payment_form_billpay_elv" class="form-list bpy-container" style="display: none">
    <li>
        <!-- Loading panel -->
        <span id="billpay-ajax-elv-container-loading" style="display:none; margin-top:10px; margin-left:25px; color:#9C9C9C; ">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" />&nbsp;
            <?php echo $this->__('loading_text'); ?>
        </span>

        <div id="billpay-ajax-container-elv">

        </div>
    </li>
</ul>
