<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php echo $this->__('billpay_rec') ?>
<br />
<img src="https://www.billpay.de/sites/default/files/LogoMid1.png" title="Billpay" alt="Billpay logo">
<?php if ($this->getOrder()):?>
	<br /><br />
	<?php if ($this->getOrder()->getBillpayInvoiceDuedate()):?>
	<?php echo $this->__('billpay_info_text2_1') ?><?php echo $this->getOrder()->getBillpayInvoiceReference() ?><?php echo $this->__('billpay_info_text2_2') ?>
	<?php echo $this->formatDate($this->getOrder()->getBillpayInvoiceDuedate()) ?>
	<?php echo $this->__('billpay_info_text2_3') ?>
	<?php else:?>
	<?php echo $this->__('billpay_info_text1_1') ?><?php echo $this->getOrder()->getBillpayInvoiceReference() ?><?php echo $this->__('billpay_info_text1_2') ?>
	<?php endif;?>
	<br /><br />
	<table>
		<tr>
			<td style="width:160px"><?php echo $this->__('billpay_account_holder') ?>:</td>
			<td><?php echo $this->getOrder()->getBillpayAccountHolder() ?></td>
		</tr>
		<tr>
			<td><?php echo $this->__('billpay_bank_name') ?>:</td>
			<td><?php echo $this->getOrder()->getBillpayBankName() ?></td>
		</tr>
        <?php if (is_numeric($this->getOrder()->getBillpayBankCode()) === false): // SEPA ?>
            <tr>
                <td><?php echo $this->__('billpay_bic') ?>:</td>
                <td><?php echo $this->getOrder()->getBillpayBankCode() ?></td>
            </tr>
            <tr>
                <td><?php echo $this->__('billpay_iban') ?>:</td>
                <td><?php echo $this->getOrder()->getBillpayAccountNumber() ?></td>
            </tr>
        <?php else: // local account ?>
            <tr>
                <td><?php echo $this->__('billpay_bank_code') ?>:</td>
                <td><?php echo $this->getOrder()->getBillpayBankCode() ?></td>
            </tr>
            <tr>
                <td><?php echo $this->__('billpay_account_number') ?>:</td>
                <td><?php echo $this->getOrder()->getBillpayAccountNumber() ?></td>
            </tr>
        <?php endif; ?>
		<tr>
			<td><?php echo $this->__('billpay_invoice_reference') ?>:</td>
			<td><?php echo $this->getOrder()->getBillpayInvoiceReference() ?></td>
		</tr>
		<?php if($this->getOrder()->getBillpayInvoiceDuedate()): ?>
		<tr>
			<td><?php echo $this->__('billpay_invoice_duedate') . ':' ?></td>
			<td><?php echo $this->formatDate($this->getOrder()->getBillpayInvoiceDuedate()) ?></td>
		</tr>
		<?php endif; ?>
	</table>
<?php endif; ?>

