<?php echo $this->getChildHtml('breadcrumbs') ?>
<div class="col-wrapper">
    <?php // This left_first block will display above the main content on smaller viewports ?>
    <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
        <div class="col-left sidebar col-left-first"><?php echo $_leftContent;   ?></div>
    <?php endif; ?>
    <div class="col-main">
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>
    </div>
    <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
</div>