<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle(); ?> - <span style="font-style:italic;"><?php echo $this->__('Account info'); ?></span><br />
    <?php $_accounts = $this->getAccounts(); ?>
    <?php foreach($_accounts as $_account): ?>
    <br />
        <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
            <label><?php echo $this->__('Account holder') ?></label>:
            <?php echo $_accountHolder ?><br />
        <?php endif; ?>
        <?php if ($_bankName = $_account->getBankName()): ?>
            <label><?php echo $this->__('Bank name') ?></label>:
            <?php echo $_bankName ?><br /><br />
        <?php endif; ?>
        <?php if (($_iban = $_account->getIban()) && ($_bic = $_account->getBic())): ?>
            <label><?php echo $this->__('IBAN') ?></label>:
            <?php echo $_iban ?><br />
            <label><?php echo $this->__('BIC') ?></label>:
            <?php echo $_bic ?>
    		<?php endif; ?>
    
    <?php endforeach; ?>
    <?php if ($_customText = $this->getMethod()->getCustomText()): ?>
        <br />
        <?php echo $_customText; ?><br />
    <?php endif; ?>
</p>
